Phase02 Section-5 completed
Star-Academy/Winter99-Codestar-MohammadReza-Sadeghi pull request #1
Opened 2021-02-25 10:03 UTC by MRSadeghi78

2021-02-25 15:26 UTC, MKasaei00 commented on Phase01/FileReader.java
> +    String path;
متغییر بهتره که خصوصی تعریف بشه
private

2021-02-25 15:27 UTC, MKasaei00 commented on Phase01/FileReader.java
> +    public FileReader(String p)
اسم پارامتر می‌تونه بهتر انتخاب بشه

2021-02-25 15:34 UTC, MKasaei00 commented on Phase01/Main.java
> +    public static void main(String[] args) throws IOException
به نظرم بهتره که استثناها به تابع اصلی برنامه نرسه
و خودتون داخل برنامه با پیغام مناسب مدیریت کنید

2021-02-25 15:35 UTC, MKasaei00 commented on Phase01/Main.java
> +        Scanner scanner = new Scanner(System.in);
بستن اسکنر فکر می‌کنم فراموش شده
scanner.close();

2021-02-25 15:37 UTC, MKasaei00 commented on Phase01/QuerySearcher.java
> +    public QuerySearcher(InvertedIndex ii)
برای اسم پارامتر فکر کنم نام های بهتری میشه انتخاب کرد

2021-02-25 15:53 UTC, MKasaei00 requested changes
سلام
چند موردی که به ذهنم رسید را ثبت کردم
به نظرم مهم‌ترین‌شون نام گذاری و خصوصی سازی فیلد‌های کلاس‌ها بود.

2021-02-25 15:53 UTC, MKasaei00 commented on Phase01/QuerySearcher.java
> +    // returns the word which has fewest docs in the index
کامنت‌ها به صورت جاوا داک نوشته بشن به نظرم مرتب تر میشه

2021-02-25 15:53 UTC, MKasaei00 commented on Phase01/QuerySearcher.java
> +        if (invertedIndex.index.get(minimumWord) == null)
دسترسی مستقیم به فیلد داخل کلاس مناسب نیست 
بهتره از توابع 
getter 
استفاده کنید

2021-02-25 15:53 UTC, MKasaei00 commented on Phase01/FileReader.java
> +        ArrayList<String> docs = new ArrayList<>();
چون متغییرها تغییر نمی‌کنند بهتره فاینال تعریف بشن

2021-02-25 15:53 UTC, MKasaei00 commented on Phase01/InvertedIndex.java
> +        FileReader fileReader = new FileReader(dataFolder);
متغییر می‌تونه فاینال باشه

2021-02-25 15:53 UTC, MKasaei00 commented on Phase01/InvertedIndex.java
>          if (docList == null)
به نظرم اگر از تابع 
`contains`
استفاده بشه کد تمیز تر میشه

2021-02-25 15:53 UTC, MKasaei00 commented on Phase01/Main.java
> +
چاپ پیغام مناسب قبل از دریافت لیست کلمات به نظرم خیلی مناسب‌تره

2021-02-25 15:53 UTC, MKasaei00 commented on Phase01/Operand.java
> +public class Operand
وظایفی که این کلاس بر عهده داره فکر کنم یه مقداری کم است
شاید خوب باشه که تعدادی از توابع کلاس‌های دیگه را در اینجا تعریف کنید

2021-02-25 15:53 UTC, MKasaei00 commented on Phase01/QuerySearcher.java
> +    InvertedIndex invertedIndex;
فیلد‌ها باید خصوصی باشند و در صورتی که نیاز به دسترسی دارید از توابع
‍‍‍‍`getter`
استفاده کنید

2021-02-25 15:53 UTC, MKasaei00 commented on Phase01/QuerySearcher.java
> +            if (invertedIndex.index.get(w) == null)
اگر از تابع 
‍‍`contains`
استفاده بشه ، تمیزتر میشه

2021-02-25 15:53 UTC, MKasaei00 commented on Phase01/QuerySearcher.java
> +public class QuerySearcher
به نظر میاد این کلاس کمی طولانی‌تر از معمول هست شاید بشه بعضی عملیات‌ها را به کلاس‌های دیگه منتقل کرد
مثل صرف اعمال اجتماع و اشتراک و ..

2021-02-25 15:57 UTC, MRSadeghi78 commented on Phase01/FileReader.java
> +    String path;
درسته ممنون

2021-02-25 15:58 UTC, MRSadeghi78 commented on Phase01/FileReader.java
> +    public FileReader(String p)
اینم اصلاحش میکنم

2021-02-25 15:59 UTC, MRSadeghi78 commented on Phase01/Main.java
> +    public static void main(String[] args) throws IOException
آره راست میگی اونجوری بهتره

2021-02-25 16:00 UTC, MRSadeghi78 commented on Phase01/Main.java
> +        Scanner scanner = new Scanner(System.in);
فکر نمیکنم خیلی مهم باشه ولی اینم اضافه میکنم

2021-02-25 16:01 UTC, MRSadeghi78 commented on Phase01/QuerySearcher.java
> +    public QuerySearcher(InvertedIndex ii)
فکر میکنم مفهوم رو میرسونن، پیشنهاد خاصی داری؟

2021-02-25 16:02 UTC, MRSadeghi78 commented on Phase01/QuerySearcher.java
> +    // returns the word which has fewest docs in the index
درست میگی، اصلاحش میکنم

2021-02-25 16:04 UTC, MRSadeghi78 commented on Phase01/QuerySearcher.java
> +        if (invertedIndex.index.get(minimumWord) == null)
آره آره ممنون که گفتی

2021-02-25 16:05 UTC, MRSadeghi78 commented on Phase01/FileReader.java
> +        ArrayList<String> docs = new ArrayList<>();
حق با توعه

2021-02-25 16:06 UTC, MRSadeghi78 commented on Phase01/InvertedIndex.java
> +        FileReader fileReader = new FileReader(dataFolder);
بازم حق با توعه

2021-02-25 16:07 UTC, MRSadeghi78 commented on Phase01/InvertedIndex.java
>          if (docList == null)
درسته

2021-02-25 16:10 UTC, MRSadeghi78 commented on Phase01/Main.java
> +
فکر میکنم منظورت قبل از خوندن ورودی از کاربر باشه و خط پایینتر کد رو میخواستی انتخاب کنی درسته؟

2021-02-25 16:16 UTC, MRSadeghi78 commented on Phase01/Operand.java
> +public class Operand
آخه واقعا کار خاصی نمیکنه، صرفا برای اینکه کد تمیزتر بشه تصمیم گرفتم
ArrayList words & HashSet docs
برای هر عملگر + یا - یا هیچکدوم رو توی یه کلاس جدید بذارم
حالا که گفتی شاید توابع مربوط به خوندن کلمات هر عملگر رو بیارم اینجا که کلاس 
QuerySearcher
هم خلوتتر بشه

2021-02-25 16:16 UTC, MRSadeghi78 commented on Phase01/QuerySearcher.java
> +    InvertedIndex invertedIndex;
درسته

2021-02-25 16:17 UTC, MRSadeghi78 commented on Phase01/QuerySearcher.java
> +            if (invertedIndex.index.get(w) == null)
آره آره درسته

2021-02-25 16:22 UTC, MRSadeghi78 commented on Phase01/QuerySearcher.java
> +public class QuerySearcher
توابعی که مربوط به محاسبه کردن
and, or, ...
هست رو به نظرم بهتره به کلاس دیگه نبریم چون اصل کار این کلاس محاسبه کردن همیناست و انتقالشون به یه کلاس دیگه میتونه یک پارچگی و خوانایی کد رو کم کنه (حالا این نظر منه اگه پیشنهادی داری خوشحال میشم بشنوم) ۰
ولی شاید توابع مربوط به کلمات هر عملگر از رشته ورودی رو ببرم تو یه کلاس دیگه

2021-02-25 16:38 UTC, MKasaei00 commented on Phase01/Main.java
> +        Scanner scanner = new Scanner(System.in);
خیلی تفاوتی نداره 
برای اصولی تر شدن گفتم :))

2021-02-25 16:38 UTC, MKasaei00 commented on Phase01/QuerySearcher.java
> +    public QuerySearcher(InvertedIndex ii)
در مورد پارامتر 
‍‍`ii`
گفتم

2021-02-25 16:39 UTC, MKasaei00 commented on Phase01/QuerySearcher.java
> +    public QuerySearcher(InvertedIndex ii)
مثلا index شاید مناسب‌تر باشه

2021-02-25 16:40 UTC, MKasaei00 commented on Phase01/Main.java
> +
بله همین محدوده منظورم بود
:))

2021-02-25 16:42 UTC, MKasaei00 commented on Phase01/QuerySearcher.java
> +public class QuerySearcher
اوکی 
فقط به عنوان پیشنهاد بود

2021-02-25 16:50 UTC, MRSadeghi78 commented on Phase01/QuerySearcher.java
> +    public QuerySearcher(InvertedIndex ii)
آهان درسته، فکر کردم اون دوتا پارامتر بالا رو میگی

2021-02-25 20:17 UTC, MKasaei00 approved these changes
خسته نباشی
به نظرم کدهات خوبه

2021-02-26 06:44 UTC, alrz1999 requested changes

2021-02-26 06:44 UTC, alrz1999 commented on Phase01/FileReader.java
> +                String fileData = scanner.useDelimiter("\\A").next();
delimeter
یه فیلد استاتیک باشه بهتره به نظرم

2021-02-26 06:44 UTC, alrz1999 commented on Phase01/InvertedIndex.java
> +    public void readData(String dataFolder)
به نظرم خوندن دیتا از فایل ربطی به 
inverted index
نداره و بهتره یه کلاس دیگه این کار رو انجام بده و 
invertedIndex
فقط یه کلاس برای نگه داری دیتا باشه

2021-02-26 06:44 UTC, alrz1999 commented on Phase01/Main.java
> +        String[] inStr = scanner.nextLine().toLowerCase().split(" ");
inStr?
بعد به نظرم یه کلاس دیگه واسه خوندن و پردازش و تمیزسازی ورودی کاربر داشته باشیم بهتره

2021-02-26 06:44 UTC, alrz1999 commented on Phase01/Main.java
> +            System.out.println(d);
همینطور برای خروجی دادن هم یه کلاس دیگه داشتیم باشیم بهتره فک کنم

2021-02-26 06:44 UTC, alrz1999 commented on Phase01/QuerySearcher.java
> +    void getAndWords(String[] inputWords)
این تابع
get
نمیکنه در واقع

2021-02-26 06:44 UTC, alrz1999 commented on Phase01/QuerySearcher.java
> +    void and(HashSet<Integer> a, HashSet<Integer> b)
اینجور چیز ها رو تو 
utility
بزاری بهتره
این کلاسه همینجوری بزرگ هستش 😄

2021-02-26 07:10 UTC, MRSadeghi78 commented on Phase01/FileReader.java
> +                String fileData = scanner.useDelimiter("\\A").next();
useDelimiter
یکی از توابع آماده کلاس 
Scanner
هست، منظورتون اینه که یه فیلد جدا براش درنظر بگیرم؟ دلیلشو نمیفهمم میشه بیشتر توضیح بدین

2021-02-26 07:14 UTC, MRSadeghi78 commented on Phase01/InvertedIndex.java
> +    public void readData(String dataFolder)
درسته، خوندن از فایل درواقع تو کلاس
FileReader
اتفاق میافته و وظیفه اصلی این تابع اضافه کردن دیتای خونده شده به ایندکس هست
شاید بهتر باشه اسمش رو 
readAndAddData
بذارم تا مفهوم رو بهتر منتقل کنه

2021-02-26 07:16 UTC, MRSadeghi78 commented on Phase01/Main.java
> +        String[] inStr = scanner.nextLine().toLowerCase().split(" ");
درسته، اصلاحش میکنم

2021-02-26 07:17 UTC, MRSadeghi78 commented on Phase01/Main.java
> +            System.out.println(d);
چون خروجی‌ای که میخوایم بدیم خیلی ساده هست و پردازش خاصی نداره گفتم شاید نیاز به این کار نباشه
ولی چشم این رو هم اصلاح میکنم

2021-02-26 07:19 UTC, MRSadeghi78 commented on Phase01/QuerySearcher.java
> +    void getAndWords(String[] inputWords)
درسته
extractAndWords
مناسبه به نظر شما ؟

2021-02-26 07:23 UTC, MRSadeghi78 commented on Phase01/FileReader.java
> +                String fileData = scanner.useDelimiter("\\A").next();
حق با شماست

2021-02-26 08:13 UTC, alrz1999 commented on Phase01/InvertedIndex.java
> +    public void readData(String dataFolder)
مشکل من بیشتر این بود که چرا
inverted index
ات باید بدونه
FileReader
چیه و باهاش کار کنه؟

2021-02-26 08:19 UTC, alrz1999 commented on Phase01/QuerySearcher.java
> +    void getAndWords(String[] inputWords)
اینم اوکیه
setAndWords
هم خوبه

2021-02-26 09:53 UTC, MRSadeghi78 commented on Phase01/InvertedIndex.java
> +    public void readData(String dataFolder)
درسته، خوندن از 
FileReader
رو به 
Main
منتقل میکنم

2021-02-26 09:54 UTC, MRSadeghi78 commented on Phase01/QuerySearcher.java
> +    void and(HashSet<Integer> a, HashSet<Integer> b)
انجام شد

2021-02-27 09:29 UTC, RAAvenger reviewed
خسته نباشی، کدت به نظرم از خیلی جنبه‌ها کد خوبیه ولی میتونه بازم بهتر بشه

2021-02-27 09:29 UTC, RAAvenger commented on Phase01/FileReader.java
> +    public FileReader(String path)
به نظرم متدهاي اين کلاس مي‌تونن به صورت استاتيک تعريف بشن، چرا که عملا نياز نداريم که از اين کلاس يک نمونه بسازيم و نمونه رو نگهداريم.

2021-02-27 09:29 UTC, RAAvenger commented on Phase01/InvertedIndex.java
> +    HashMap<String, HashSet<Integer>> getIndex()
از اونجايي که 
inverted index
در عمل حکم پایگاه داده‌ی تو رو داره پیشنهاد می‌کنم به جای برگردوندن داده ساختار خامت که ممکنه در طول توسعه پروژه تغییر کنه توابعی برای دسترسی به عناصر درون داده ساختارت بنویسی که نیاز نباشه کل داده ساختار رو برگردونی.

2021-02-27 09:29 UTC, RAAvenger commented on Phase01/Main.java
> +        ArrayList<String> docs = fileReader.read();
این دو خط میتونن ترکیب بشن چون نیازی به نگهداری فایل ریدر نیست.

2021-02-27 09:29 UTC, RAAvenger commented on Phase01/Operand.java
> +public class Operand
دست کم میتونی توابع پیشنیاز برای سرچ کردن و مقایسه کردن رو توی کلاست بازنویسی کنی.
منظورم توابعی مثل 
equals(object , object)
هست.

2021-02-27 09:29 UTC, RAAvenger commented on Phase01/Output.java
> +public class Output
هدف از تعریف این کلاس رو متوجه نمیشم، واقعا لازمه؟

2021-02-27 09:29 UTC, RAAvenger commented on Phase01/QuerySearcher.java
> +    private Operand excludeOperands = new Operand();
با توجه به این ساختار هر بار که نیاز باشه عمل سرچ انجام بشه باید یک نمونه از این کلاس ساخته بشه؟ یا فقط عملوندها رو عوض میکنی( اینجوری برای همروندی( وقتی که بخوای چندتا سرچ رو همزمان انجام بدی ) مشکل ایجاد نمیشه؟ )؟

2021-02-27 09:29 UTC, RAAvenger commented on Phase01/QuerySearcher.java
> +public class QuerySearcher
به نظرم ساختار این کلاس چندان مطلوب نیست مخصوصا به این دلیل که تعدادی از متغییر‌ها به صورت صفات کلاس تعیین شدن و این کار میتونه موجب کم شدن انعطاف پذیری برنامه و همچنین ذخیره شدن داده‌هایی که واقعا نیازی به نگهداریشون نیست بشه.

2021-02-27 09:29 UTC, RAAvenger commented on Phase01/Tokenizer.java
> +    }
به نظرم این تابع به این کلاس تعلق نداره، چرا که عملا توکنایز کردن و ارتباط با کاربر دوتا فعالیت مجزا هستن

2021-02-27 09:29 UTC, RAAvenger commented on Phase01/Tokenizer.java
> +    }
بیشتر این کدا تکراریه و یک سویچ کیس میتونه انتخاب بهتری باشه.

2021-02-27 09:29 UTC, RAAvenger commented on Phase01/Util.java
> +    static void and(HashSet<Integer> a, HashSet<Integer> b)
نامگذاریای تک حرفی در اکثر مواقع باعث پایین اومدن قابلیت خوانایی میشه

2021-02-27 09:29 UTC, RAAvenger commented on Phase01/Util.java
> +     * @param a list of words
کدوم پارامتر؟ :)

2021-02-27 09:29 UTC, RAAvenger commented on Phase01/Util.java
> +public class Util
به طور کلی مشکل خاصی توی این کلاس ندیدم ولی حس میکنم متدها میتونستن یکم بهتر طراحی بشن.

2021-02-27 10:20 UTC, MRSadeghi78 commented on Phase01/FileReader.java
> +    public FileReader(String path)
همممم... حق با توعه
ممنون

2021-02-27 10:21 UTC, MRSadeghi78 commented on Phase01/InvertedIndex.java
> +    HashMap<String, HashSet<Integer>> getIndex()
آره درسته، اصلاحش میکنم

2021-02-27 10:22 UTC, MRSadeghi78 commented on Phase01/Main.java
> +        ArrayList<String> docs = fileReader.read();
برای خوانایی بهتر اینطوری نوشتم

2021-02-27 10:26 UTC, MRSadeghi78 commented on Phase01/Output.java
> +public class Output
توصیه آقا علیرضا بود
فکر میکنم بیشتر بخاطر این باشه که شاید در آینده بخوایم متدهای مختلفی برای چاپ کردن داشته باشیم و همچنین
Main 
خلوتتر بشه

2021-02-27 10:27 UTC, MRSadeghi78 commented on Phase01/QuerySearcher.java
> +    private Operand excludeOperands = new Operand();
باید یه نمونه جدید ساخته بشه و اینطوری تو مالتی ترد هم به مشکل نمیخوره

2021-02-27 10:34 UTC, MRSadeghi78 commented on Phase01/Tokenizer.java
> +    }
اینجا منظور از توکنایز کردن، توکنایز کردن ورودی کاربر هست نه داکیومنت ها
بخاطر همین به نظرم بهتره که این توابع کنار هم تو یه کلاس باشن
البته حرف تو هم درسته و فکر میکنم اگه اسم کلاس رو به
InputTokenizer
تغییر بدم این ابهام برطرف بشه

2021-02-27 10:37 UTC, MRSadeghi78 commented on Phase01/Tokenizer.java
> +    }
فکر میکنم اینطوری خواناییش بیشتر باشه
همچنین اگه روزی بخوایم فقط کلمات مخصوص به یه عملگر رو استخراج کنیم، استفاده از این توابع فکر میکنم ساده تر باشه

2021-02-27 10:39 UTC, MRSadeghi78 commented on Phase01/Util.java
> +    static void and(HashSet<Integer> a, HashSet<Integer> b)
برای توابع پیچیده حق با توعه، ولی برای یه تابع ساده مثل
swap
واقعا نیازی نیست پارامتر ها اسم خاصی داشته باشن
اینجا هم همین قضیه هست، دو تا مجموعه رو ورودی میگیریم و 
and 
میکنیم، با این حال توضیحات تکمیلی رو توی جاواداک تابع نوشتم

2021-02-27 10:41 UTC, MRSadeghi78 commented on Phase01/Util.java
> +     * @param a list of words
کلمه
words
جا افتاده بود، ممنون بابت دقت نظر

2021-02-27 10:41 UTC, MRSadeghi78 commented on Phase01/Util.java
> +public class Util
منظورت اسمشونه یا کاراییشون یا اینکه مثلا مربوط به این کلاس نباید باشن یا چی؟

2021-02-27 12:18 UTC, MKasaei00 requested changes
چند تا تغییر به ذهنم رسید نوشتم 
برنامه خیلی تمیزتر میشه

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/FileReader.java
> +    static String delimiter = "\\A";
به نظر میاد این فیلد می‌تونه
private , final 
باشه

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/FileReader.java
> +                docs.add(fileData.toLowerCase());
به نظر میاد تبدیل برخی حروف بزرگ به کوچک به نوعی نرمال‌سازی محتوای فایل هست
فکر می‌کنم به کلاس 
Tokenizer 
مرتبطه و می‌شه به عنوان تابع جدا باشه

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/FileReader.java
> +        ArrayList<String> docs = new ArrayList<>();
این متغییر هم می‌تونه فاینال باشه

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/InvertedIndex.java
> +    public void addData(ArrayList<String> docs)
طراحی این کلاس قابلیت بهتر شدن داره
فرض کن می‌خواهیم داده‌ها را به مرور به پایگاه داده اضافه کنیم وقتی اندیس داکیومنت‌ها به عنوان شناسه قرار بگیره اگر یک بار مثلا یه آرایه ۱۰ تایی و بار دوم هم یه آرایه‌ی ۱۰ تایی به پایگاه اضافه کنیم 
در عمل شناسه‌ها از ۰ تا ۹ هست 
و داکیومنت‌ها به درستی متمایز نمی‌شن

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/InvertedIndex.java
> +    public void addData(ArrayList<String> docs)
از طرفی بازیابی داده‌ها هم خیلی نکته پیدا میشه

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/InvertedIndex.java
>              docList.add(doc);
دستور
docList.add(doc);
در هر دو حالت شرط وجود داره
می‌تونه فقط یک بار بعد از شرط نوشته بشه

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/Output.java
> +public class Output
به نظرم این کلاس جای بهبود داره
فکر می‌کنم آقا علیرضا بیش‌تر منظورشون این بوده که تمام بحث تعامل با کاربر از لحظه اول شروع برنامه که ورودی گرفتن هست تا چاپ کردن داده‌ها و خاتمه دادن به برنامه باید با کلاس جدا باشه
در اینصورت تابع اصلی فقط وظیفه فراخوانی یک تابع مثل
start
را پیدا میکنه و بقیه‌ی کارها از نظر تابع اصلی مستقل از روش ارتباط خواهد بود.

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/QuerySearcher.java
> +    void setAndWords(String[] inputWords)
به نظرم مناسب‌تره که سطح دسترسی توابع به صورت صریح 
private 
تعریف بشن که دسترسی از کلاس‌های دیگر محدود بشه

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/QuerySearcher.java
> +    void setAndWords(String[] inputWords)
بقیه‌ی توابع هم همینطور

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/Tokenizer.java
> +        String inputStr = readInputFromUser();
می‌تونه فاینال تعریف بشه

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/Tokenizer.java
> +        Scanner scanner = new Scanner(System.in);
می‌تونه فاینال تعریف بشه

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/Tokenizer.java
> +        String inputStr = scanner.nextLine();
می‌تونه فاینال تعریف بشه

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/Tokenizer.java
> +    }
منم با رضا موافقم
بهتره که ارتباط با کاربر از توکن کردن مجزا باشه

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/Util.java
> +        }
به نظرم اگر از تابع 
removeif
استفاده بشه کد تمیز تر میشه

2021-02-27 12:18 UTC, MKasaei00 commented on Phase01/Util.java
> +
به نظرم اگر از تابع
removeif
استفاده بشه کد تمیز تر میشه

2021-02-27 12:22 UTC, MRSadeghi78 commented on Phase01/FileReader.java
> +    static String delimiter = "\\A";
بله درسته، ممنون

2021-02-27 12:41 UTC, MRSadeghi78 commented on Phase01/FileReader.java
> +                docs.add(fileData.toLowerCase());
حق با شماست، اصلاح شد

2021-02-27 12:41 UTC, MRSadeghi78 commented on Phase01/FileReader.java
> +        ArrayList<String> docs = new ArrayList<>();
درسته

2021-02-27 12:46 UTC, MRSadeghi78 commented on Phase01/InvertedIndex.java
> +    public void addData(ArrayList<String> docs)
درسته، در اصل شناسه داکیومنت ها رو با این فرض که همه شون داخل یک پوشه قرار دارند و قراره که یک بار خونده بشن، ساخته میشه
مطمئنا اگه بخوایم چند بار داکیومنت‌های مختلف از جاهای مختلف بخونیم، شناسه گذاری و ذخیره کردنشون یه چالش دیگه هست.

2021-02-27 12:50 UTC, MRSadeghi78 commented on Phase01/InvertedIndex.java
>              docList.add(doc);
درسته

2021-02-27 13:57 UTC, RAAvenger commented on Phase01/Tokenizer.java
> +    }
الان حدس میزنم تو یک مجموعه 
inputWords
رو به سه تا تابع میدی و هرتابع یک بار کل این ارایه رو پیمایش میکنه که یعنی در عمل سه بار یک ارایه رو پیمایش میکنی.
حالا این اتفاق روی سرعت برنامه تاثیر خیلی شدیدی نداره ولی به نظرم این بهینگی‌های کوچیک میتونن باعث بهتر شدن نتیجه نهایی بشن.

2021-02-27 13:59 UTC, RAAvenger commented on Phase01/Util.java
> +public class Util
اسما که در نظر من مشکل خاصی ندارن، ولی حس کردم مجموعه کارایی که بین متدها تقسیم کردی میتونستن به شکل بهتری تقسیم بشن، ولی صرفا حس کردم

2021-02-27 15:11 UTC, MRSadeghi78 commented on Phase01/Util.java
> +        }
نکته خوبی بود
ممنون

2021-02-27 15:11 UTC, MRSadeghi78 commented on Phase01/Util.java
> +
تغییرش دادم
ممنون

2021-02-27 15:22 UTC, mohammadhheidarzade approved these changes

2021-02-27 20:04 UTC, alrz1999 approved these changes

2021-02-28 12:42 UTC, RAAvenger approved these changes

2021-03-01 17:47 UTC, merged