Phase03 completed
Star-Academy/Winter99-Codestar-MohammadReza-Sadeghi pull request #3
Opened 2021-03-03 15:50 UTC by MRSadeghi78

2021-03-03 15:59 UTC, mohammadhheidarzade requested changes
کد کاورج چند شده؟

2021-03-03 15:59 UTC, mohammadhheidarzade commented on Phase03/test/TestFileReader.java
> +//    @Test
کامنت های پاک بشه

2021-03-03 15:59 UTC, mohammadhheidarzade commented on Phase03/test/TestQuerySearcher.java
> +        assertEquals(new HashSet<Integer>(), querySearcher.getAndOperands().getDocs());
هر تابع تست یک assert 
باید استفاده باشه

2021-03-03 15:59 UTC, mohammadhheidarzade commented on Phase03/test/TestQuerySearcher.java
> +    void testAndResults()
تابع خیلی بزرگه
وهر تابع تست یک assert
استفاده بشه

2021-03-03 15:59 UTC, mohammadhheidarzade commented on Phase03/test/TestQuerySearcher.java
> +        assertEquals(new HashSet<Integer>(), result);
هر تابع یک assert

2021-03-03 16:44 UTC, MKasaei00 requested changes
تست‌ها کامل بود
فقط به نظرم مهم‌ترین نکات طول زیاد تست‌ها و عدم پیاده‌سازی تابع آماده‌سازی قبل از تست‌ها بود.

2021-03-03 16:44 UTC, MKasaei00 commented on Phase03/src/FileReader.java
> +            scanner = new Scanner(file);
تعریف اسکنر می‌تونه در یک خط انجام بشه

2021-03-03 16:44 UTC, MKasaei00 commented on Phase03/src/InputTokenizer.java
> +        String inputStr = readInputFromUser();
به نظرم این تابع با 
Single responsibility
سازگار نیست
خواندن ورودی از کاربر و توکن کردن دو کار متفاوته

2021-03-03 16:44 UTC, MKasaei00 commented on Phase03/src/Util.java
> +     */
این کامنت‌ها به نظرم اضافی هست
چون مطلب جدیدی نداره و اسم تابع واضح هست

2021-03-03 16:44 UTC, MKasaei00 commented on Phase03/src/Util.java
> +     */
کامنت توضیح جدیدی نمی‌ده

2021-03-03 16:44 UTC, MKasaei00 commented on Phase03/test/TestFileReader.java
> +            docs.add("h>subject to a high-voltag");
می‌تونیم اضافه کردن را در تابع 
constructor
انجام بدیم 
به نظرم کد تمیز تر میشه

2021-03-03 16:44 UTC, MKasaei00 commented on Phase03/test/TestFileReader.java
> +            docs.add("h>subject to a high-voltag");
بعضا جاهای دیگه هم تکرار شده

2021-03-03 16:44 UTC, MKasaei00 commented on Phase03/test/TestQuerySearcher.java
> +    }
به نظرم این کاری هست که قبل از هر تست لازمه انجام بشه
پس بهتره یک تابع با تعریف
@Before
تعریف بشه و به طور کلی کارایی که برای آماده‌سازی محیط تست هست انجام بشه

2021-03-04 14:05 UTC, MRSadeghi78 commented on Phase03/test/TestQuerySearcher.java
> +    }
چون توی نصف تابع های این کلاس از
InvertedIndex
استفاده نمیشه، به نظرم گذاشتنش توی
before
خیلی کار صحیحی نیست

2021-03-04 14:08 UTC, MRSadeghi78 commented on Phase03/test/TestFileReader.java
> +            docs.add("h>subject to a high-voltag");
چون کلا یه تابع تو کلاس هست و فقط دوتا استرینگ به لیست اضافه میکنم، شاید اینکار واقعا لزومی نداشته باشه

2021-03-04 14:10 UTC, MRSadeghi78 commented on Phase03/src/Util.java
> +     */
درسته که اسم تابع واضحه، ولی اگه دقت کنی تابع از جنس 
void
هست، یعنی چیزی برنمیگردونه. پس به نظرم لازمه توضیح بدیم که نتیجه
and
دو مجموعه کجا ذخیره میشه

2021-03-04 14:11 UTC, MRSadeghi78 commented on Phase03/src/Util.java
> +     */
برای تابع
and
توضیح دادم

2021-03-04 14:13 UTC, MRSadeghi78 commented on Phase03/src/InputTokenizer.java
> +        String inputStr = readInputFromUser();
اینو چند جلسه پیش با علیرضا بحثشو کردیم. چون اینجا فقط ورودی رو توکنایز میکنیم و کاری که انجام میدیم تقریبا در جهت همون ورودی گرفتنه، ایرادی نداره که هردوی اینها توی یه کلاس باشن

2021-03-04 14:14 UTC, MRSadeghi78 commented on Phase03/src/FileReader.java
> +            scanner = new Scanner(file);
درسته

2021-03-04 15:02 UTC, MRSadeghi78 commented on Phase03/test/TestFileReader.java
> +//    @Test
یادم رفته بود
ممنون

2021-03-04 15:03 UTC, MRSadeghi78 commented on Phase03/test/TestQuerySearcher.java
> +        assertEquals(new HashSet<Integer>(), querySearcher.getAndOperands().getDocs());
اصلاح شد

2021-03-04 15:03 UTC, MRSadeghi78 commented on Phase03/test/TestQuerySearcher.java
> +    void testAndResults()
اصلاح شد

2021-03-04 15:03 UTC, MRSadeghi78 commented on Phase03/test/TestQuerySearcher.java
> +        assertEquals(new HashSet<Integer>(), result);
درسته
اصلاحش کردم

2021-03-05 15:35 UTC, RAAvenger commented on Phase03/test/TestInvertedIndex.java
> +        docs.add(" Banks  N3JXP      | \"Skep");
این جوری هم میشه 
new ArrayList<>(Arrays.toList(" text", "text"));

2021-03-05 15:35 UTC, RAAvenger commented on Phase03/test/TestQuerySearcher.java
> +    }
فکر کنم عین این تابع رو یه جای دیگه هم نوشته بودی، میتونی یه کلاس جدید بسازی برای این توابع مشترک.

2021-03-05 15:35 UTC, RAAvenger commented on Phase03/test/TestQuerySearcher.java
> +    }
اگر توی تابع 
before
نوشته بشه یک بار انجام میشه؟
اگر اینطوره که بهتره توی همون تابع 
before
بنویسیش.

2021-03-05 15:35 UTC, RAAvenger commented on Phase03/test/TestQuerySearcher.java
> +        docs.add(0);
hashSet
رو هم میشه اونجوری که بالاتر برات نوشتم با 
Arrays.toList()
ایجاد کرد

2021-03-06 19:57 UTC, mohammadhheidarzade approved these changes

2021-03-07 08:40 UTC, MKasaei00 approved these changes

2021-03-07 13:54 UTC, alrz1999 requested changes
به نظرم بهتره تو اسم کلاس ها و توابع تست
Test
آخرش بیاد
https://stackoverflow.com/questions/3146821/naming-convention-junit-suffix-or-prefix-test/3146984

2021-03-07 13:54 UTC, alrz1999 commented on Phase03/SampleData/b.txt
> +h>subject to a high-voltag
کلا این دایرکتوری
SampleData
میرفت تو
test
بهتر نبود؟

2021-03-07 13:54 UTC, alrz1999 commented on Phase03/src/FileReader.java
> +        for (File file: listOfFiles != null ? listOfFiles : new File[0])
اینو بعد از خط 10 چک کنی و بریزی تو همون
listOfFiles
 بهتر نیست؟
این 
for
یه مقدار تمیز نیست به نظر

2021-03-07 13:54 UTC, alrz1999 commented on Phase03/src/InputTokenizer.java
> +        String inputStr = readInputFromUser();
من حرفمو پس میگیرم😅
به نظرم یه کلاس ریز بزن تمیز تر شه😁

2021-03-07 13:54 UTC, alrz1999 commented on Phase03/src/InputTokenizer.java
> +        return inputStr.toLowerCase().split("\\s+");
این 
رجکسه
هم
final static 
بشه به نظر بهتره

2021-03-07 13:54 UTC, alrz1999 commented on Phase03/src/InvertedIndex.java
> +            String[] words = docs.get(i).split("\\W+");
رجکس 
final static

2021-03-07 13:54 UTC, alrz1999 commented on Phase03/src/Main.java
> +        invertedIndex.addData(docs);
خط های 
8 9 10 14
رو میشه برد تو یه تابع تو همین 
Main
که یه 
QuerySearcher
خروجی بده

2021-03-07 13:54 UTC, alrz1999 commented on Phase03/src/Main.java
> +        ArrayList<String> docs = FileReader.read("EnglishData/");
آدرس فایل هم
final static
بشه بهتره به نظر

2021-03-07 13:54 UTC, alrz1999 commented on Phase03/test/TestUilt.java
> +public class TestUilt
TestUilt 😱😱

2021-03-07 15:05 UTC, MRSadeghi78 commented on Phase03/src/InputTokenizer.java
> +        String inputStr = readInputFromUser();
جداشون کردم

2021-03-07 15:11 UTC, MRSadeghi78 commented on Phase03/src/FileReader.java
> +        for (File file: listOfFiles != null ? listOfFiles : new File[0])
درسته، اصلاحش کردم

2021-03-07 15:17 UTC, MRSadeghi78 commented on Phase03/src/InputTokenizer.java
> +        return inputStr.toLowerCase().split("\\s+");
درسته، اصلاحش کردم

2021-03-07 15:18 UTC, MRSadeghi78 commented on Phase03/src/InvertedIndex.java
> +            String[] words = docs.get(i).split("\\W+");
اصلاح شد

2021-03-07 15:21 UTC, MRSadeghi78 commented on Phase03/src/Main.java
> +        invertedIndex.addData(docs);
درسته

2021-03-07 19:03 UTC, MRSadeghi78 commented on Phase03/src/Main.java
> +        ArrayList<String> docs = FileReader.read("EnglishData/");
حق با شماست، درستش کردم

2021-03-07 19:03 UTC, MRSadeghi78 commented on Phase03/test/TestUilt.java
> +public class TestUilt
:)

2021-03-07 20:09 UTC, MRSadeghi78 commented on Phase03/test/TestQuerySearcher.java
> +    }
اگه قبلش 
@BeforeAll
بذارم فقط یه بار قبل از همه اجرا میشه ولی خب نمیتونم این کارو بکنم چون تو بعضی توابع محتویات ایندکس تغییر میکنه. با این حال برای خوانا تر شدن کد یه
@BeforeEach
قبلش گذاشتم تا اول هرتابع مجبور نشم صداش کنم

2021-03-07 20:14 UTC, alrz1999 approved these changes

2021-03-07 20:16 UTC, MRSadeghi78 commented on Phase03/test/TestInvertedIndex.java
> +        docs.add(" Banks  N3JXP      | \"Skep");
فکر میکنم اینجوری خوانایی بهتر باشه، حالا اینجا خیلی معلوم نیست ولی جاهای دیگه که آیتم‌های زیادی رو میخوام به لیست اضافه کنم، این شکلی که تو میگی شاید یه کم گیج کننده باشه

2021-03-07 20:32 UTC, MRSadeghi78 commented on Phase03/test/TestQuerySearcher.java
> +    }
آره اینو خودمم میخواستم تو ریفکتور درستش کنم یادم رفت. ممنون که گفتی

2021-03-07 20:35 UTC, MRSadeghi78 commented on Phase03/SampleData/b.txt
> +h>subject to a high-voltag
درسته، ممنون که گفتین
اصلاحش کردم

2021-03-08 07:00 UTC, merged