Phase04 c sharp
Star-Academy/Winter99-Codestar-MohammadReza-Sadeghi pull request #4
Opened 2021-03-08 07:09 UTC by MRSadeghi78

2021-03-08 07:40 UTC, MKasaei00 reviewed
کد خوبی بود. :)
چند مورد ساده بود نوشتم

2021-03-08 07:40 UTC, MKasaei00 commented on Phase04/Phase04/Scores.json
> +    "StudentNumber": 1,
فایل‌های تست بهتره از مخرن حذف بشن

2021-03-08 07:40 UTC, MKasaei00 commented on Phase04/Phase04/Students.json
> +  {
فایل داده‌های ورودی بهتره از مخرن حذف بشن

2021-03-08 07:40 UTC, MKasaei00 commented on Phase04/Phase04/Program.cs
> +        static void Main(string[] args)
به نظرم این تابع یه مقدار طولانیه 
شاید بشه با تجزیه این تابع کد را مرتب تر کرد

2021-03-08 07:40 UTC, MKasaei00 commented on Phase04/Phase04/Program.cs
> +                Console.WriteLine(student.FirstName + " " + student.LastName + " : " + scores.Where(s => s.StudentNumber == student.StudentNumber).Average(s => s.Score));
قسمت محاسبه میانگین بهتره به صورت خط جدا باشه
چون این خط وظیفه چاپ را داره

2021-03-08 07:40 UTC, MKasaei00 commented on Phase04/Phase04/Program.cs
> +            Console.WriteLine();
این قسمت جزو صورت سوال نبود
ولی حضورش ضرری هم نداره

2021-03-08 18:07 UTC, mohammadhheidarzade approved these changes

2021-03-08 22:11 UTC, RAAvenger requested changes
سلام
برنامه‌ت به خوبی کار میکنه
ولی اصلا ساختارش صحیح نیست
به نظرم همه کد رو داخل یک
main
نوشتن حتی در حد همین برنامه کوچیک هم کار جالبی نیست

2021-03-08 22:11 UTC, RAAvenger commented on .gitignore
>  EnglishData/
فایل های فاز 3 رو اشتباهی اوردی توی برنچ فاز 4. :)

2021-03-08 22:11 UTC, RAAvenger commented on .gitignore
>  EnglishData/
بهتره بعدا بیشتر مراقب باشی

2021-03-08 22:11 UTC, RAAvenger commented on .gitignore
>  EnglishData/
و 
gitignore 
رو به صورت لوکال نگهدار
اینجوری از این مشکلات هم پیش نمیاد

2021-03-08 22:11 UTC, RAAvenger commented on Phase04/Phase04/Program.cs
> +}
کل لاجیکت رو یه جا نوشتی؟ نه کلاسی نه 
S.O.L.I.D.
رسما ساختار خاصی اعمال نکردی

2021-03-09 09:50 UTC, MRSadeghi78 commented on Phase04/Phase04/Program.cs
> +}
راستش فکر میکردم هدف از این فاز صرفا یادگیری کد زدن با سی شارپ و آشنایی با لینک و اینجور چیزهاست. اصلا به ساختار کد توجه نکردم، حق با توعه خیلی کثیف شده. اصلاحش میکنم

2021-03-09 09:54 UTC, MRSadeghi78 commented on .gitignore
>  EnglishData/
چون گیت ایگنور از 
master
اومده، فایل های مربوط به فاز های قبلی هم توش هست، دقیقا متوجه مشکل نشدم

2021-03-09 09:55 UTC, MRSadeghi78 commented on Phase04/Phase04/Program.cs
> +            Console.WriteLine();
چون نفهمیدم منظور صورت سوال کدوم حالته، هر دوتاش رو نوشتم
ولی اگه منظور از ۳ دانشجوی اول، براساس معدل بوده، این قسمتو پاک میکنم

2021-03-09 09:57 UTC, MRSadeghi78 commented on Phase04/Phase04/Program.cs
> +                Console.WriteLine(student.FirstName + " " + student.LastName + " : " + scores.Where(s => s.StudentNumber == student.StudentNumber).Average(s => s.Score));
درسته درسته، بیشتر برای تمرین لینک سعی کردم همشو تو یه خط بنویسم
ولی خب کل این قسمتو پاک میکنم

2021-03-09 09:58 UTC, MRSadeghi78 commented on Phase04/Phase04/Program.cs
> +        static void Main(string[] args)
حق با توعه. چون پروژه برای آشنایی با سی شارپ بود به ساختارش خیلی دقت نکردم

2021-03-09 09:58 UTC, MRSadeghi78 commented on Phase04/Phase04/Students.json
> +  {
درسته

2021-03-09 09:58 UTC, MRSadeghi78 commented on Phase04/Phase04/Scores.json
> +    "StudentNumber": 1,
درسته

2021-03-09 11:58 UTC, RAAvenger commented on .gitignore
>  EnglishData/
خب يک سري فايلا اين وسط ايگنور نشدن
فايلاي فاز قبلي.

2021-03-09 13:41 UTC, MRSadeghi78 commented on .gitignore
>  EnglishData/
درسته
چون این فاز ربطی به فاز های قبل نداره بهتره کل فاز های قبلی رو بذارم تو گیت ایگنور. منظورت اینه؟

2021-03-09 14:35 UTC, MRSadeghi78 commented on .gitignore
>  EnglishData/
آره الان دیدم
عجیبه توی گیت ایگنور هستن ولی ایگنور نشدن

2021-03-10 12:32 UTC, RAAvenger approved these changes

2021-03-10 14:30 UTC, alrz1999 commented on Phase04/Phase04/FileReader.cs
> +        public static string Read(string FilePath)
filePath

2021-03-10 14:30 UTC, alrz1999 commented on Phase04/Phase04/Program.cs
> +        static IEnumerable<StudentAverage> FindTop3Students(List<Student> Students, List<Mark> Scores)
این هم میتونست
generic
تر باشه و عدد 3 رو ورودی بگیره و جاش هم اینجا نیست به نظر

2021-03-10 14:30 UTC, alrz1999 commented on Phase04/Phase04/Program.cs
> +            var scores = Parser.jsonToList<Mark>(FileReader.Read("../../../Scores.json"));
آدرس فایل ها هم یه متغیر استاتیک باشه بهتره به نظر

2021-03-13 10:51 UTC, MRSadeghi78 commented on Phase04/Phase04/FileReader.cs
> +        public static string Read(string FilePath)
حق با شماست، نمیدونم چرا فکر میکردم آرگومان های تابع ها باید پاسکال باشن

2021-03-13 12:26 UTC, MRSadeghi78 commented on Phase04/Phase04/Program.cs
> +        static IEnumerable<StudentAverage> FindTop3Students(List<Student> Students, List<Mark> Scores)
این که کلی تر میتونست باشه درسته
ولی اینکه جاش اینجا نیست، چون کار کلاس
Program
محاسبه کردن دانشجوهای با بیشترین معدله، به نظرم گذاشتنش تو این کلاس مخالف
single responsibility
نیست، حالا باز اگه موافق نیستی میبرمش تو یه کلاس جدید

2021-03-13 12:27 UTC, MRSadeghi78 commented on Phase04/Phase04/Program.cs
> +            var scores = Parser.jsonToList<Mark>(FileReader.Read("../../../Scores.json"));
درسته

2021-03-13 16:51 UTC, alrz1999 approved these changes

2021-03-13 17:02 UTC, MKasaei00 approved these changes

2021-03-14 07:15 UTC, merged