Phase05 tdd
Star-Academy/Winter99-Codestar-MohammadReza-Sadeghi pull request #5
Opened 2021-03-11 20:27 UTC by MRSadeghi78

2021-03-13 08:04 UTC, MKasaei00 requested changes
خسته نباشی 
خوب بود.

چند مورد به ذهنم رسید . کامنت گذاشتم

2021-03-13 08:04 UTC, MKasaei00 commented on Phase05/Phase05/Operations.cs
> +                    var wordDocs = Index.Index[Words[i]];
به نظرم بهتره یه تابع برای سرچ وجود داشته باشه
و کدهای خارج کلاس وابسته به ساختار دیکشنری داخلی نباشه

2021-03-13 08:04 UTC, MKasaei00 commented on Phase05/Phase05/Tokenizer.cs
> +        public static (List<string>, List<string>, List<string>) ExtractQuery(string Query)
پارامتر 
Query
باید 
camelCase
باشه

2021-03-13 08:04 UTC, MKasaei00 commented on Phase05/Phase05/Tokenizer.cs
> +        public static string[] SplitInput(string Input)
به نظرم این تابع بیش‌تر به کلاس‌های کنسول مرتبط هست تا این کلاس
(با این که عملکرد مشابهی با 
tokenizer
داره ولی به نظرم از نظر مفهومی مرتبط نیست.)

2021-03-13 08:04 UTC, MKasaei00 commented on Phase05/Phase05/Operations.cs
> +            return BaseSet;
به نظرم بهتره که تعداد تابع واسط در کلاس
InvertedIndex 
طراحی بشه تا وابستگی مستقیم به ساختار دیکشنری موجود در کلاس از بین برود.


برای مثال کد بالا کاملا به ساختار درونی کلاس 
InvertedIndex 
وابسته است.

2021-03-13 08:04 UTC, MKasaei00 commented on Phase05/Phase05/Operations.cs
> +            return BaseSet;
توابع دیگر این کلاس هم تقریبا همین‌طور هستند.

2021-03-13 08:04 UTC, MKasaei00 commented on Phase05/Phase05/InvertedIndex.cs
> +            Index[key] = docs;
فکر می‌کنم 
چون متغییر‌ها در 
C#
به صورت ارجاع هستند نیازه نیست دوباره آرایه را در دیکشنری مقدار دهی کنی

2021-03-13 08:04 UTC, MKasaei00 commented on Phase05/Phase05/Input.cs
> +    public class Input
به نظرم این کلاس می‌تونه با کلاس 
output
ادغام بشه 
چون خحم کاری که این کلاس انجام می‌ده واقعا کم هست و از طرفی از نظر مفهومی ورودی و خروجی به نوعی به هم وابسته هستند.

2021-03-13 08:04 UTC, MKasaei00 commented on Phase05/Phase05/Tokenizer.cs
> +        public static string[] SplitDocument(string Document)
پارامتر باید به صورت 
camelCase
نام‌گذاری بشه

2021-03-13 08:04 UTC, MKasaei00 commented on Phase05/Phase05/Tokenizer.cs
> +        public static string Tokenize(string Str)
Parameter camelCase

2021-03-13 08:04 UTC, MKasaei00 commented on Phase05/Test/TokenizerTest.cs
> +            Assert.Equal(new List<string> { "issue" }, exWords);
می‌تونه این تابع به سه تابع تفکیک بشه تا درصورتی که یکی از تست‌ها خطا داد 
دقیقا مشخص بشه که مشکل از چه بخشی به وجود آمده

2021-03-13 08:04 UTC, MKasaei00 commented on Phase05/Phase05/FileReader.cs
> +                Console.WriteLine("Invalid path :)");
بهتره که این پیغام هم از طریق کلاس 
output
چاپ بشه که 
Single responsibility
بهتر رعایب بشه

2021-03-13 15:04 UTC, MRSadeghi78 commented on Phase05/Phase05/Tokenizer.cs
> +        public static string[] SplitInput(string Input)
ببین درسته که اینجا ورودی رو فقط با اسپیس جدا میکنیم، ولی شاید در آینده بخوایم توکنایز های دیگه‌ای هم روش اجرا کنیم. پس از لحاظ مفهومی به نظرم بهتره که تو این کلاس باشه

2021-03-13 15:05 UTC, MRSadeghi78 commented on Phase05/Phase05/Tokenizer.cs
> +        public static string[] SplitInput(string Input)
چون به هر حال داریم ورودی رو توکنایز میکنیم، هرچند این توکنایز کردن کار ساده‌ای مثل جدا کردن کلمات با اسپیس باشه

2021-03-13 15:07 UTC, MRSadeghi78 commented on Phase05/Test/TokenizerTest.cs
> +            Assert.Equal(new List<string> { "issue" }, exWords);
درسته

2021-03-13 15:07 UTC, MRSadeghi78 commented on Phase05/Phase05/FileReader.cs
> +                Console.WriteLine("Invalid path :)");
درسته

2021-03-13 15:11 UTC, MRSadeghi78 commented on Phase05/Phase05/Input.cs
> +    public class Input
به نظرم اینطوری تمیزتره، درسته که الان فقط یه تابع توی کلاس های ورودی و خروجی داریم ولی اگه روزی بخوایم به شکل های مختلف ورودی بگیریم و خروجی های متفاوتی بدیم، جدای از اینکه کلاسمون خیلی شلوغ میشه، با مفهوم تک وظیفه‌ای بودن هم ناسازگاری داره

2021-03-13 15:17 UTC, MRSadeghi78 commented on Phase05/Phase05/InvertedIndex.cs
> +            Index[key] = docs;
در اون صورت باید یه شرط
if else
بگذارم که اگه اون کلید توی دیکشنری موجود نبود، از اول بسازمش و در غیر این صورت مقدار فعلی رو آپدیت کنم که فکر میکنم کد فعلی خواناتر باشه (جدای از اینکه توی حجم کد تفاوتی ایجاد نمیکنه)

2021-03-13 15:20 UTC, MRSadeghi78 commented on Phase05/Phase05/Operations.cs
> +            return BaseSet;
واقعا لازمه؟ چون به نظرم این کار ساختار ساده توابع فعلی رو قطعا پیچیده‌تر میکنه

2021-03-13 15:37 UTC, MKasaei00 commented on Phase05/Phase05/InvertedIndex.cs
> +            Index[key] = docs;
بله 
درسته

2021-03-13 15:39 UTC, MKasaei00 commented on Phase05/Phase05/Tokenizer.cs
> +        public static string[] SplitInput(string Input)
اوکی حله

2021-03-13 15:40 UTC, MKasaei00 commented on Phase05/Phase05/Operations.cs
> +            return BaseSet;
به نظرم بهتره که اون اتفاق بیفته و دسترسی به فیلد‌ها محدود بشه

ولی باعث می‌شه یه تابع‌هایی اضافه بشه که ممکنه کد را پیچیده کنه
هر طور صلاح می‌دونی عمل کن

2021-03-13 15:42 UTC, MKasaei00 commented on Phase05/Phase05/Input.cs
> +    public class Input
درسته از هر دو نظر میشه به مسئله نگاه کرد
از یک نظر هم ورودی و خروجی به نوعی با هم وابسته‌اند و با کنسول کار می‌کنیم

2021-03-14 15:01 UTC, RAAvenger reviewed
کد خيلي خوبي بود
خسته نباشي

2021-03-14 15:01 UTC, RAAvenger commented on Phase05/Phase05/InvertedIndex.cs
> +        public virtual Dictionary<string, HashSet<int>> Index { get; }
چرا ويرچوال؟

2021-03-14 15:01 UTC, RAAvenger commented on Phase05/Phase05/InvertedIndex.cs
> +                var docWords = Tokenizer.SplitDocument(tokenizedDoc);
اسپليت کردن نبايد موقع توکنايز کردن انجام بشه؟

2021-03-14 15:01 UTC, RAAvenger commented on Phase05/Phase05/InvertedIndex.cs
> +            Index[key] = docs;
اگر از 
tryGetValue
استفاده کني تميزتره

2021-03-14 15:01 UTC, RAAvenger commented on Phase05/Phase05/Operations.cs
> +        public static HashSet<int> OrWords(List<string> words, InvertedIndex index)
ميتوني 
index
رو داخل خود کلاس نگهداري

2021-03-14 15:01 UTC, RAAvenger commented on Phase05/Phase05/Tokenizer.cs
> +        }
سر اين کار( توليد اين مدل خروجي ) قبلا من رو نقد کردن

2021-03-14 15:01 UTC, RAAvenger commented on Phase05/Test/InvertedIndexTest.cs
> +        public void AddToIndexTest2()
سناريوي اين تست دوم چيه؟

2021-03-14 15:01 UTC, RAAvenger commented on Phase05/Test/InvertedIndexTest.cs
> +        public void AddToIndexTest2()
نقدم به نوع نامگذاريه

2021-03-14 15:02 UTC, RAAvenger approved these changes
کد خيلي خوبي بود، خسته نباشي

2021-03-14 16:29 UTC, MRSadeghi78 commented on Phase05/Phase05/InvertedIndex.cs
> +        public virtual Dictionary<string, HashSet<int>> Index { get; }
چون
setter
نداره توی ماک کردن به مشکل میخورد. سرچ کردم گفته بودن که با ویرچوال کردنش درست میشه

2021-03-14 16:31 UTC, MRSadeghi78 commented on Phase05/Phase05/InvertedIndex.cs
> +                var docWords = Tokenizer.SplitDocument(tokenizedDoc);
نه لزوما. چون توکنایز یه کاریه که هم برای داکیومنت ها و هم برای کویری های ورودی انجام میشه، ولی اسپلیت (به این شکل) فقط برای داکیومنت هاست

2021-03-14 16:32 UTC, MRSadeghi78 commented on Phase05/Phase05/Operations.cs
> +        public static HashSet<int> OrWords(List<string> words, InvertedIndex index)
فکر نمیکنم کار جالبی باشه. فرض کن چندتا ایندکس داریم و میخوایم همزمان از توابع این کلاس استفاده کنیم، اینجوری به مشکل میخوره

2021-03-14 16:33 UTC, MRSadeghi78 commented on Phase05/Phase05/Tokenizer.cs
> +        }
به نظر من که اینجوری تمیزتر میشه (و خلاصه‌تر)
حالا بازم با بچه ها درموردش صحبت میکنیم

2021-03-14 17:29 UTC, mohammadhheidarzade approved these changes

2021-03-14 18:07 UTC, MRSadeghi78 commented on Phase05/Test/InvertedIndexTest.cs
> +        public void AddToIndexTest2()
تابع هایی که به شکل
XTEST[number]
تست هایی هستن که حالت های مختلف تابع 
X
رو تست میکنن و به نظرم نام گزاری بدی نیست چون نشون میده هرتابع تست دقیقا داره کدوم تابع رو تست میکنه

2021-03-14 18:54 UTC, alrz1999 reviewed
یه پوشه بندی هم بکن بیزحمت😅

2021-03-14 18:54 UTC, alrz1999 commented on Phase05/Phase05/Tokenizer.cs
> +        public static (List<string>, List<string>, List<string>) ExtractQuery(string query)
این خروجی ها رو یه کلاس بزاری بهتر نیست؟

2021-03-14 18:54 UTC, alrz1999 commented on Phase05/Phase05/Tokenizer.cs
> +        }
عه اینجا گفتینش :))

2021-03-14 18:54 UTC, alrz1999 commented on Phase05/Test/Creator.cs
> +    class Creator
خیلی اسم کلی ایه

2021-03-14 18:54 UTC, alrz1999 commented on Phase05/Test/TokenizerTest.cs
> +            Assert.Equal("tus in  some people8. there is a nati", Tokenizer.Tokenize(doc));
به نظرم وقتی 
doc
رو داری از یه کلاس دیگه میگیری
expected
رو هم از همونجا بگیری بهتره چون اونجا تغییر کنه اینجا هم باید تغییر کنه

2021-03-15 06:49 UTC, MRSadeghi78 commented on Phase05/Test/Creator.cs
> +    class Creator
ObjectCreator
بهتره؟

2021-03-15 06:50 UTC, MRSadeghi78 commented on Phase05/Test/TokenizerTest.cs
> +            Assert.Equal("tus in  some people8. there is a nati", Tokenizer.Tokenize(doc));
درسته ممنون

2021-03-15 06:53 UTC, MRSadeghi78 commented on Phase05/Test/Creator.cs
> +    class Creator
SampleCreator یا

2021-03-15 07:15 UTC, MRSadeghi78 commented on Phase05/Phase05/Tokenizer.cs
> +        public static (List<string>, List<string>, List<string>) ExtractQuery(string query)
به ۳ تابع جدا تقسیمشون کردم

2021-03-15 07:16 UTC, MRSadeghi78 commented on Phase05/Phase05/Tokenizer.cs
> +        }
به ۳ تابع جدا تقسیمشون کردم

2021-03-15 08:21 UTC, MRSadeghi78 commented on Phase05/Phase05/InvertedIndex.cs
> +            Index[key] = docs;
درسته ممنون

2021-03-15 09:09 UTC, merged