Ef core
Star-Academy/Winter99-Codestar-MohammadReza-Sadeghi pull request #7
Opened 2021-03-27 19:45 UTC by MRSadeghi78

2021-03-28 13:57 UTC, MKasaei00 commented on Phase08/Phase05/IO/File/FileReader.cs
> +                    if (!content.Equals(""))
به نظرم بهتره از تابع
empty
استفاده بشه

2021-03-28 13:57 UTC, MKasaei00 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +            return result;
متغییر 
result
به نظرم اضافیه

2021-03-28 13:57 UTC, MKasaei00 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +            return (HashSet<int>) docs;
به نظرم بهتره متغییر از اول با نوع مناسب تعریف بشه و نیازی به 
cast 
نباشه

2021-03-28 13:57 UTC, MKasaei00 commented on Phase08/Phase05/Utils/Operations.cs
> +    public class Operations
به عنوان یه پیشنهاد :
 اگر از این کلاس یک شی بسازی و 
invertedIndex
را به عنوان پارامتر سازنده به کلاس وارد کنی
و با شی کلاس کار کنی و نیازی نیست که در تابع 
index
را پارامتر بدی

2021-03-28 13:57 UTC, MKasaei00 commented on Phase08/Phase05/Program.cs
> +                .UseSqlServer(@"Server=.\MRSADEGHI78;Database=InvertedIndexDB;Trusted_Connection=True;")
اگر آدرس سرور و نام پایگاه داده به صورت متغییر جدا و ثابت تعریف بشه به نظرم بهتره

2021-03-29 17:47 UTC, RAAvenger requested changes
<div dir="rtl">
سلام</br>
خسته نباشی</br>
کد بسیار خوبیه</br>
به نظرم اینکه برای نامگذاری توابع تست از اسم تابع مورد تست و عدد استفاده کردی کار درستی نیست و وقتی چندتا تست کیس مختلف داری یا باید توی داکیومنت بنویسی که هرکدوم چیکار میکنن یا توی اسمشون 
</div>

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Phase05/DataSet/Document.cs
> +        public string Content { get; set; }
<div dir="rtl">
وقتي که ما ميتونيم با id مستقيم به داکيومنت‌ها دسترسي داشته باشيم آيا لازمه خود داکيومنت رو نگهداريم؟
</div>

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Phase05/DataSet/WordDoc.cs
> +        public int DocId { get; set; }
<div dir="rtl">
اين رو ميشه به سادگي از خود Doc گرفت
</div>

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Phase05/DataSet/WordDoc.cs
> +    public class WordDoc
کلمه يا توکن؟ مساله اين است :)

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Phase05/IO/File/FileReader.cs
> +                    if (!content.Equals(""))
<div dir="rtl">
فکر کنم يه تابع هست به نام EmptyOrWhiteSpase
</div>

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Phase05/Search/InvertedIndex.cs
> +        public DbSet<WordDoc> WordDocs { get; set; }
فکر نکنم عملا به اين احتياجي بشه

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Phase05/Search/InvertedIndex.cs
> +        public InvertedIndex() { }
لازمه؟

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Phase05/Search/InvertedIndex.cs
> +                .HasForeignKey(wd => wd.DocId);
فکر کنم بشه اينا رو با هم ترکيب کرد

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Phase05/Search/InvertedIndex.cs
> +    public class InvertedIndex : DbContext
<div dir="rtl">
به نظرم بهتره که inverted index  و پايگاه داده‌ش دوتا کلاس مجزا باشن و عملکرداشون با هم ترکيب نشن
</div>

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Phase05/Search/SearchEngine.cs
> +            List<string> exWords = Tokenizer.ExtractExcludeWords(query);
براي استخراج سه تا دسته فيلتر داري سه بار يک رشته رو توکنايز ميکني و بعد هم پيمايشش ميکني، بهتره که فقط يک بار اين دوتا کار انجام بشن

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Phase05/Search/SearchEngine.cs
> +                    result = Operations.AndWords(andWords, result, Index);
<div dir="rtl">
ميتوني اين شرط رو ببري داخل AndWors
</div>

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Phase05/Utils/Tokenizer.cs
> +            return Regex.Split(input, "\\s+");
<div dir="rtl">
همونجور که regex کلمات رو جدا ذخیره کردی میتونی این رو هم توی خود کلاس ذخیره کنی
</div>

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Test/IOTest/FileTest/FileReaderTest.cs
> +        public void ReadFromFolderTest2()
<div dir="rtl">
این داره یه مسیر غلط رو بررسی میکنه؟</br>
از اسمش که معلوم نیست و چون من نمیدونم که آیا فولدر abc وجود داره یا نه از کدش هم نمیتونم برداشت درستی بکنم.
</div>

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Test/IOTest/FileTest/FileReaderTest.cs
> +            string path = @"../../../../Test/SampleData/";
میتونی توی سازنده این مسیر و داده‌های داخلش رو بسازی و موقع از بین بردن کلاس مسیر رو پاک کنی

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Test/SearchTest/InvertedIndexTest.cs
> +            Assert.Equal(1, invertedIndex.Documents.Count());
<div dir="rtl">
یه دونه Assert کافیه، همچنین بهتره برای تستات از کلمات متفاوت استفاده کنی که تقریبا تمام اشکالات احتمالی  رو پوشش بدی برای حالتی که تستا روی یه ابجکت مشترک اجرا بشن
</div>

2021-03-29 17:47 UTC, RAAvenger commented on Phase08/Test/SearchTest/SearchEngineTest.cs
> +        }
به نظرم بهتره چندتا کیس دیگه رو هم تست کنی( جهت کار از محکم کاری عیب نمیکنه )

2021-04-02 08:05 UTC, MRSadeghi78 commented on Phase08/Phase05/IO/File/FileReader.cs
> +                    if (!content.Equals(""))
درسته. اصلاحش کردم

2021-04-02 08:08 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +            return result;
درسته

2021-04-02 08:09 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +            return (HashSet<int>) docs;
درسته

2021-04-02 08:14 UTC, MRSadeghi78 commented on Phase08/Phase05/Utils/Operations.cs
> +    public class Operations
موافق نیستم
اینجا یه کلاس داریم که فقط از توابعش استفاده میکنم و درنتیجه همه تابع‌هاش استاتیک هستن، حالا اینکه بیایم این توابع رو از استاتیک دربیاریم و با شیئ کلاس کار کنیم فکر نمیکنم خیلی درست باشه چون عملا از شی کلاس استفاده‌ای نمیشه

2021-04-02 08:15 UTC, MRSadeghi78 commented on Phase08/Phase05/Program.cs
> +                .UseSqlServer(@"Server=.\MRSADEGHI78;Database=InvertedIndexDB;Trusted_Connection=True;")
کاملا درسته

2021-04-02 08:26 UTC, MRSadeghi78 commented on Phase08/Phase05/DataSet/Document.cs
> +        public string Content { get; set; }
فرض بر اینه که خود داکیومنت ها رو توی رَم نداریم و همه چیز توی دیتابیس ذخیره شده، درنتیجه با آیدی نمیتونیم مستقیم به داکیومنت ها دسترسی داشته باشیم

2021-04-02 08:30 UTC, MRSadeghi78 commented on Phase08/Phase05/DataSet/WordDoc.cs
> +        public int DocId { get; set; }
DocId
رو میگی؟
توی مثال ما که یه تعداد داکیومنت محدود داریم که اسم همشون متمایزه میشه اینکارو کرد ولی توی حالت کلی نه

2021-04-02 08:34 UTC, MRSadeghi78 commented on Phase08/Phase05/DataSet/WordDoc.cs
> +    public class WordDoc
چون توی بخش های دیگه کد برای اسم متغیرا و تابعا و اینا از
word
استفاده کرده بودم، اینجا هم کلمه نوشتم ولی خب حق با توعه، توکن دقیقتره

2021-04-02 08:35 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +        public DbSet<WordDoc> WordDocs { get; set; }
چرا؟

2021-04-02 08:36 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +        public InvertedIndex() { }
توی بعضی تست ها استفاده میشه

2021-04-02 08:37 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +                .HasForeignKey(wd => wd.DocId);
این قسمتو از روی خود سایت
EFCore
برداشتم. چون خیلی بهش مسلط نبود ترجیح دادم که تغییرش ندم

2021-04-02 08:40 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +    public class InvertedIndex : DbContext
آخه اینجا
inverted index
داره نقش پایگاه داده رو بازی میکنه و این دوتا در عمل یک مفهومن

2021-04-02 08:42 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/SearchEngine.cs
> +            List<string> exWords = Tokenizer.ExtractExcludeWords(query);
ای بابااا
آقا برا فاز ۵ من دقیقا همین کارو کرده بودم ولی نظر جمع (از جمله خودت!) این بود که بهتره اینا رو جدا کنیم تا خوانایی کد بیشتر بشه :)

2021-04-02 08:59 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/SearchEngine.cs
> +                    result = Operations.AndWords(andWords, result, Index);
به نظرم اصل تک وظیفه‌ای بودن رو نقض میکنه
اینجا ما داریم تصمیم میگیریم که نتیجه کلمات
or
شده رو هم باید
and
بکنیم یا نه که مربوط به هندل کردن کوئری میشه. درحالی که کار 
AndWords
فقط
and
کردن کلماته

2021-04-02 08:59 UTC, MRSadeghi78 commented on Phase08/Phase05/Utils/Tokenizer.cs
> +            return Regex.Split(input, "\\s+");
آره احتمالا یادم رفته بود. ممنون

2021-04-02 09:07 UTC, MRSadeghi78 commented on Phase08/Test/IOTest/FileTest/FileReaderTest.cs
> +        public void ReadFromFolderTest2()
اسمش رو اصلاح کردم

2021-04-02 09:12 UTC, MRSadeghi78 commented on Phase08/Test/SearchTest/InvertedIndexTest.cs
> +            Assert.Equal(1, invertedIndex.Documents.Count());
استفاده از کلمات مختلف توی تست های دیگه که مربوط به بحث کوئری ها میشن کاملا لحاظ شده. اینجا فقط هدف اینه که ببینیم یه کلمه به دیتابیس اضافه میشه یا نه
و اینکه چطوری با یه 
assert
این رو تست کنم؟

2021-04-02 11:00 UTC, RAAvenger commented on Phase08/Phase05/DataSet/WordDoc.cs
> +        public int DocId { get; set; }
<div dir="rtl">
ببین وقتی اومدی از شیئ document و word استفاده کردی، دیگه نیاز نیست که یک فیلد جدا برای idهاشون هم داشته باشی
</div>

2021-04-02 11:03 UTC, RAAvenger commented on Phase08/Phase05/Search/InvertedIndex.cs
> +        public DbSet<WordDoc> WordDocs { get; set; }
<div dir="rtl">
کافیه که برای نوع document یک مجموعه word و برای نوع word یک مجموعه document اتعریف کنی، اینجوری خود entity framwork برات جدول میانی رو ایجاد میکنه
</div>

2021-04-02 11:05 UTC, RAAvenger commented on Phase08/Phase05/Search/InvertedIndex.cs
> +        public InvertedIndex() { }
public InvertedIndex() { }?
اینو که خود سی شارپ به طور پیشفرض ایجاد میکنه

2021-04-02 11:08 UTC, RAAvenger commented on Phase08/Phase05/Search/InvertedIndex.cs
> +                .HasForeignKey(wd => wd.DocId);
[page link](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#join-entity-type-configuration)
modelBuilder
    .Entity<Post>()
    .HasMany(p => p.Tags)
    .WithMany(p => p.Posts)

2021-04-02 11:12 UTC, RAAvenger commented on Phase08/Phase05/Search/InvertedIndex.cs
> +    public class InvertedIndex : DbContext
<div dir="rtl">
چونکه خود مفهوم inverted index رو عملا با پایگاه داده عوض کردی، اره.
ولی خب inverted index در عمل یه جور پایگاه داده‌س و sql database هم یه جور دیگه از پایگاه داده‌س.
</div>

2021-04-02 11:14 UTC, RAAvenger commented on Phase08/Phase05/Search/SearchEngine.cs
> +            List<string> exWords = Tokenizer.ExtractExcludeWords(query);
اونجا مشکل این بود که ورودی و خروجیای تابع جوری بودن که به نوع فیلترها وابسته بودن

2021-04-02 11:16 UTC, RAAvenger commented on Phase08/Phase05/Search/SearchEngine.cs
> +                    result = Operations.AndWords(andWords, result, Index);
<div dir="rtl">
حرفم این بود که ممکنه بتونی از روی مقدار result تشخیص بدی وضعیت orWords رو و نیاز نباشه که دوتا تابع داشته باشی برای andWords.
</div>

2021-04-02 11:20 UTC, RAAvenger commented on Phase08/Test/SearchTest/InvertedIndexTest.cs
> +            Assert.Equal(1, invertedIndex.Documents.Count());
```c#
invertedIndex.Documents.where(d => d.Content==str)->count()
```

2021-04-02 12:34 UTC, MRSadeghi78 commented on Phase08/Phase05/DataSet/WordDoc.cs
> +        public int DocId { get; set; }
آهان تازه فهمیدم. ببین من چندتا مثال تو اینترنت نگا کردم همشون همین کارو کرده بودن، شاید یه جور عرفه، نمیدونم

2021-04-02 12:38 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +        public DbSet<WordDoc> WordDocs { get; set; }
آهان جالبه. توی خود سایتش این شکلی تعریف کرده بود
[ef core many to many](https://www.entityframeworktutorial.net/efcore/configure-many-to-many-relationship-in-ef-core.aspx)

2021-04-02 12:40 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +        public InvertedIndex() { }
نه دیگه اون برا وقتیه که خودت کانستراکتور تعریف نکرده باشی در اون صورت خود سی شارپ یدونه پیش فرض میسازه
من چون خودم یه کانستراکتور دیگه دارم این کارو نمیکنه

2021-04-02 12:46 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +    public class InvertedIndex : DbContext
من هنوز معتقدم باید یکی باشن، ولی خب بذار ببینیم نظر بقیه چیه. اگه اونا هم موافق نبودن عوضش میکنم

2021-04-02 12:53 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/SearchEngine.cs
> +            List<string> exWords = Tokenizer.ExtractExcludeWords(query);
آره میشه به جای اون مثلا لیست ها رو به عنوان ورودی به تابع داد یا یه کلاس جدا براشون ساخت که خروجی از جنس اون کلاس باشه، ولی به نظر من اینطوری کد کثیف میشه و از طرفی چون سایز کوئری معمولا خیلی کمتر از دیتابیسه، ۳ بار پیمایش کردنش عملا تاثیری روی اُردر و زمان نهایی نداره

2021-04-02 12:59 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/SearchEngine.cs
> +                    result = Operations.AndWords(andWords, result, Index);
نه لزوما نمیشه از روی
result
همچین نتیجه‌ای گرفت. فرض کن
orWords
یه تعداد کلمه باشن که هیچکدوم توی هیچ یک از داکیومنت ها نیومدن. در این صورت
result
خالیه ولی تعداد
orWords
صفر نیست

2021-04-02 15:54 UTC, MKasaei00 commented on Phase08/Phase05/Utils/Operations.cs
> +    public class Operations
اگر با شی کار کنی 
می‌تونی 
invertedindex
را در مقدار دهی و سازنده در اختیار بذاری و تعداد پارامتر‌های هر تابع در کلاس کم میشه
و تابع های غیر استاتیک از همان فیلد موجود در شی استفاده می‌کنند

2021-04-02 19:53 UTC, MRSadeghi78 commented on Phase08/Test/IOTest/FileTest/FileReaderTest.cs
> +            string path = @"../../../../Test/SampleData/";
حق با توعه. ممنون بابت پیشنهادت

2021-04-02 20:00 UTC, MRSadeghi78 commented on Phase08/Test/SearchTest/InvertedIndexTest.cs
> +            Assert.Equal(1, invertedIndex.Documents.Count());
اینی که میگی درسته ولی دقیق نیست. این کد چک میکنه که همون کلمه ای که میخواستیم به دیتابیس اضافه کنیم فقط یه بار اضافه شده باشه، ولی اینکه کلمه دیگه‌ای هم (اشتباهی) در کنارش به دیتابیس اضافه نشه، چک نمیشه

2021-04-03 13:48 UTC, mohammadhheidarzade approved these changes

2021-04-03 15:37 UTC, alrz1999 requested changes

2021-04-03 15:37 UTC, alrz1999 commented on Phase08/Phase05/IO/File/FileReader.cs
> +        public static List<string> ReadFromFolder(string pathFolder)
folderPath?😅

2021-04-03 15:37 UTC, alrz1999 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +    public class InvertedIndex : DbContext
منم با رضا موافقم و به نظرم باید جدا بشن

2021-04-03 15:37 UTC, alrz1999 commented on Phase08/Phase05/Program.cs
> +            invertedIndex.CreateIndex(documents);
این قسمت مربوط به دیتابیسش میتونست یه تابع جدا شه

2021-04-03 15:37 UTC, alrz1999 commented on Phase08/Phase05/Utils/Operations.cs
> +    public class Operations
من با محمد و موافقم چون اینجا همه ی توابعت یه 
‍`InvertedIndex`
به عنوان ورودی گرفتن

2021-04-03 15:37 UTC, alrz1999 commented on Phase08/Test/IOTest/FileTest/FileReaderTest.cs
> +            Assert.Equal(new List<string> { }, FileReader.ReadFromFolder(path));
میشه جای یه لیست خالی ازین
‍`Enumerable.Empty<TResult>`
استفاده کرد ولی اینجا خیلی مهم نیست

2021-04-03 19:24 UTC, MRSadeghi78 commented on Phase08/Phase05/IO/File/FileReader.cs
> +        public static List<string> ReadFromFolder(string pathFolder)
روم سیاه🤦‍♂️ اصلاحش میکنم

2021-04-03 22:23 UTC, RAAvenger commented on Phase08/Phase05/DataSet/WordDoc.cs
> +        public int DocId { get; set; }
فکر نکنم همچین کانونشنی باشه

2021-04-03 22:23 UTC, RAAvenger commented on Phase08/Phase05/Search/InvertedIndex.cs
> +        public DbSet<WordDoc> WordDocs { get; set; }
دوتا رو گفته :)

2021-04-03 22:26 UTC, RAAvenger commented on Phase08/Phase05/Search/SearchEngine.cs
> +                    result = Operations.AndWords(andWords, result, Index);
<div dir="rtl">
میتونی مقدار پیشفرض result رو null بدی و خروجی orWords توی این حالتی که گفتی یه لیست خالی باشه
</div>

2021-04-03 22:28 UTC, RAAvenger commented on Phase08/Test/SearchTest/InvertedIndexTest.cs
> +            Assert.Equal(1, invertedIndex.Documents.Count());
خب اگر این کیسی که داری میگی ممکنه اتفاق بیافته حق با تو هستش :)

2021-04-04 06:08 UTC, MRSadeghi78 commented on Phase08/Phase05/Search/SearchEngine.cs
> +                    result = Operations.AndWords(andWords, result, Index);
همممم. درسته

2021-04-10 10:37 UTC, alrz1999 commented on Phase08/Phase05/DataSet/WordDoc.cs
> +        public int DocId { get; set; }
https://www.entityframeworktutorial.net/efcore/configure-many-to-many-relationship-in-ef-core.aspx

2021-04-10 10:37 UTC, alrz1999 commented on Phase08/Phase05/DataSet/InvertedIndexContext.cs
> +    public class InvertedIndexContext : DbContext
فقط اگه این
`InvertedIndexDbContext`
بشه بهتره😅

2021-04-10 10:37 UTC, alrz1999 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +                        AddToIndex(word, docId);
https://stackoverflow.com/questions/1930982/when-should-i-call-savechanges-when-creating-1000s-of-entity-framework-object

2021-04-12 15:37 UTC, MKasaei00 approved these changes

2021-04-12 18:19 UTC, RAAvenger approved these changes

2021-04-23 05:17 UTC, alrz1999 commented on Phase08/Phase05/Search/InvertedIndex.cs
> +        public void AddWord(string word)
`AddWord`
و
`AddIndex`
اگه بیرون استفاده نمیشن بهتره
`private`
بشن چون دارن یه چیزی رو اضافه میکنن ولی
save
نمیکنن و اگه از بیرون به تنهایی فراخوانی بشن کارشون درست انجام نمیشه
در کل هم این هر جا لازمه
`public`
بزار

2021-04-23 05:17 UTC, alrz1999 approved these changes

2021-04-25 14:37 UTC, merged